json.id receiver.id
json.category receiver.category
json.name receiver.name
json.document receiver.document
json.bank_code receiver.bank_code
json.agency receiver.agency
json.agency_dv receiver.agency_dv
json.account receiver.account
json.account_dv receiver.account_dv
