json.id arrearage.id
json.receiver_id arrearage.receiver_id
json.payment_type arrearage.payment_type
json.category arrearage.category
json.title arrearage.title
json.description arrearage.description
json.total_value arrearage.total_valu
json.installment_number arrearage.installment_number
json.payd arrearage.payd
json.pay_at arrearage.pay_at