default: &default
  adapter: mysql2
  encoding: utf8
  username: root
  password:

production:
  adapter: pg
  encoding: utf8
  database: get_coins_production
  username: get_coins
  password: <%= ENV['GET_COINS_DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: get_coins_development
  min_messages: warning
  username: root
  password:

test:
  <<: *default
  database: get_coins_test
  min_messages: warning
  username: root
  password: