default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

production:
  <<: *default
  database: get_coins_production
  username: <%= ENV['GET-COINS-BACKEND_DATABASE_USERNAME'] %>
  password: <%= ENV['GET-COINS-BACKEND_DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: get_coins_development
  min_messages: warning
  username: Leonardo
  password: 

test:
  <<: *default
  database: get_coins_test
  min_messages: warning
  username: Leonardo
  password: 