default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

production:
  <<: *default
  database: get_coins_production
  username: get_coins
  password: <%= ENV['GET_COINS_DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: get_coins_development
  min_messages: warning
  username: leonardo
  password:

test:
  <<: *default
  database: get_coins_test
  min_messages: warning
  username: leonardo
  password: